set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

default: build

build:
  cabal build

run *args:
  cabal run rambutan -- {{args}}

watch:
  ghciwatch \
    --command "cabal repl test:rambutan-test" \
    --watch src --watch app --watch test \
    --test-ghci Main.main

test:
  cabal test

fix:
  git ls-files '*.hs' | xargs -n 1 hlint --refactor --refactor-options="--inplace"
  fourmolu -i src
  fourmolu -i app
  fourmolu -i -o -XImportQualifiedPost -o -XOverloadedRecordDot test

fix-build: fix build
